const data = {
    products: [
        {   
            _id: 1,
            name:'Áo kaki Quảng Châu',
            slug: 'Ao kaki quang chau',
            category: 'ao',
            img: '/images/dataImg1.jpg',
            price: 199,
            countInStock: 4,
            brand: 'gucci',
            rating: 4.5,
            numReview: 14,
            description: 'Áo sơ mi kaki nam là một trong những trang phục đơn giản, cá tính và thời thượng dành cho mọi chàng trai. Đây cũng là món đồ không thể thiếu trong tủ quần áo và vào những dịp dạo phố hay tụ tập bạn bè',
            countProduct: 1
        },
        {
            _id: 2,
            name:'Set đồ ngắn tay',
            slug: 'set do ngan tay',
            category: 'ao, quan',
            img: '/images/dataImg2.jpeg',
            price: 99,
            countInStock: 3,
            brand: 'adidas',
            rating: 4.1,
            numReview: 88,
            description: 'Bộ đũi nam được thiết kế theo đúng form chuẩn của nam giới Việt Nam',
            countProduct: 1
        },
        {
            _id: 3,
            name:'Set đồ lịch lãng quý ông',
            slug: 'set do lich lang',
            category: 'ao, quan',
            img: '/images/dataImg3.jpeg',
            price: 999,
            countInStock: 0,
            brand: 'adidas',
            rating: 3.4,
            numReview: 30,
            description: 'Mặc set này phải nói không cần tán gái auto ',
            countProduct: 1
        },
        {
            _id: 4,
            name:'Set đồ gút boi ',
            slug: 'set do goodboy',
            category: 'ao, quan',
            img: '/images/dataImg4.jpg',
            price: 250,
            countInStock: 15,
            brand: 'chanel',
            rating: 4.9,
            numReview: 398,
            description: 'Một set đồ mà các goodboy không thể bỏ lỡ, mình phắc boi nên không cần :))',
            countProduct: 1
        },
        {
            _id: 5,
            name:'Áo khoác bò',
            slug: 'ao khoac bo',
            category: 'ao',
            img: '/images/dataImg6.jpg',
            price: 88,
            countInStock: 0,
            brand: 'chanel',
            rating: 4.5,
            numReview: 14,
            description: 'Áo khoác jean unisex nam nữ TH Store màu xanh cào xước áo khoác bò phong cách ulzzang',
            countProduct: 1
        },
        {
            _id: 6,
            name:'Giay thể thao ',
            slug: 'giay the thao',
            category: 'giay',
            img: '/images/dataImg5.jpg',
            price: 60,
            countInStock: 15,
            brand: 'nike',
            rating: 3.0,
            numReview: 14,
            description: 'Giày vans caro lười quai dán hàng 11 ban trung cao cấp full size nam nữ đủ phụ kiện túi hộp',
            countProduct: 1
        },
        {
            _id: 7,
            name:'Giày nam',
            slug: 'giay nam fake',
            category: 'giay',
            img: '/images/dataImg6.jpg',
            price: 25,
            countInStock: 8,
            brand: 'nike',
            rating: 4.5,
            numReview: 14,
            description: '(Hàng Trung) Giày nike af1 gucci nam nữ, giày nike air force 1 gucci phiên bản đặc biệt hàng đẹp - TS store',
            countProduct: 1
        },
        {
            _id: 8,
            name:'Giay nam',
            slug: 'boot dep',
            category: 'giay',
            img: '/images/dataImg7.jpg',
            price: 88,
            countInStock: 0,
            brand: 'nike',
            rating: 0.9,
            numReview: 0,
            description: 'Giày Quảng Châu, tuy fake loại n nhưng được cái bán giá rõ cao',
            countProduct: 1
        },
        {
            _id: 9,
            name:'Boot',
            slug: 'boot quang chau',
            category: 'giay',
            img: '/images/dataImg8.jpg',
            price: 79,
            countInStock: 15,
            brand: 'adidas',
            rating: 4.5,
            numReview: 17,
            description: 'Tên sản phẩm: Giày Combat Boots Zip Black ( Giày Chiến Binh ), đế tăng chiều cao, tăng 3,5cm',
            countProduct: 1
        },
        {
            _id: 10,
            name:'Giày 2',
            slug: 'giay 2',
            category: 'giay',
            img: '/images/dataImg9.jpg',
            price: 99,
            countInStock: 15,
            brand: 'vans',
            rating: 2.9,
            numReview: 33,
            description: 'Nhập data để tạo rest APi quá mỏi tay',
            countProduct: 1
        },
        {
            _id: 11,
            name:'Boot tiếp',
            slug: 'boot fake',
            category: 'giay',
            img: '/images/dataImg10.jpg',
            price: 99,
            countInStock: 15,
            brand: 'vans',
            rating: 4.5,
            numReview: 14,
            description: 'Vừa rẻ lại còn đẹp nữa chứ, hốt đi nào everyone',
            countProduct: 1
        } 
    ]
}

export default data;